apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jdownloader-config-pvc
  namespace: homelab
  labels:
    app: jdownloader
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
