apiVersion: v1
kind: Service
metadata:
  name: jdownloader
  namespace: homelab
  labels:
    app: jdownloader
spec:
  type: NodePort
  ports:
    - name: http
      port: 5800
      targetPort: 5800
      nodePort: 30580
      protocol: TCP
    - name: vnc
      port: 5900
      targetPort: 5900
      nodePort: 30590
      protocol: TCP
  selector:
    app: jdownloader
