version: '2'

services:
  iobroker:
    container_name: iobroker
    image: buanet/iobroker
    hostname: iobroker
    restart: always
    volumes:
      - iobrokerdata:/opt/iobroker
    ports:
      - "3000:80"
    environment:
      - VIRTUAL_HOST=iobroker.sandharlanden.maerz
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=iobroker.sandharlanden.maerz
      - LETSENCRYPT_EMAIL=webmaster@sandharlanden.maerz
    network_mode: bridge

  frontproxy:
    restart: always
    image: jwilder/nginx-proxy
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
    network_mode: bridge

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=mail@yourdomain.tld
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge

volumes:
  iobrokerdata:
  conf:
  vhost:
  html:
  certs:
  acme:
