services:
  iobroker:
    container_name: iobroker
    image: buanet/iobroker
    hostname: iobroker
    restart: always
    volumes:
      - iobrokerdata:/opt/iobroker
    ports:
      - "8081:8081"
volumes:
  iobrokerdata: