apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-config
  namespace: homelab
  labels:
    app: pihole
data:
  TZ: "Europe/Berlin"
  PIHOLE_DNS_: "1.1.1.1;1.0.0.1"
  DNSSEC: "true"
  QUERY_LOGGING: "true"
  WEBTHEME: "default-dark"
  # REV_SERVER settings for local DNS resolution via Unifi Gateway
  REV_SERVER: "true"
  REV_SERVER_DOMAIN: "sandharlanden.maerz"
  REV_SERVER_TARGET: "192.168.1.1"
  REV_SERVER_CIDR: "192.168.1.0/24"
