apiVersion: v1
kind: Secret
metadata:
  name: pihole-secret
  namespace: homelab
  labels:
    app: pihole
type: Opaque
stringData:
  # IMPORTANT: Change this password before deploying!
  WEBPASSWORD: "Bkar0ckt!?"
